### ISSUE TITLE
php errors

### ISSUE THREAD

**Issue by 2babooblabla** [betweenbrain/Menu-Wrench#20] opened 2014-09-04 14:24 UTC
Hello again,

Since this morning I get this error and page goes blank :+1: Notice: Undefined property: stdClass::$id in .../modules/mod_menuwrench/helper.php on line 101 Notice: Undefined property: stdClass::$params in .../mod_menuwrench/helper.php on line 107 Fatal error: Call to a member function get() on a non-object in .../modules/mod_menuwrench/helper.php on line 107 

If I unpublish your menu all goes back to normal.

Site is stille under dev so maybe I did something wrong.

I uploaded last version of mudule in case but problem persists.

thanks in advance!

Paul

**Comment by betweenbrain** [comment] 2014-09-04 15:26
Hello,

Can you tell me what changed with the site that caused this error to suddenly appear? I'm not seeing that error locally, so we'll need to figure out what caused it and how to reproduce it.

**Comment by 2babooblabla** [comment] 2014-09-04 16:17
I have added a lot of meny items.. about 200
I tried unpublishing half of then and everything goes back to normal.
So the problem certainly is related to that
Helps?

**Comment by betweenbrain** [comment] 2014-09-04 16:25
Yes, that certainly helps. But, I will need to know the exact menu item type / configuration... etc. to be able to reproduce and resolve. If you can provide that, I can work on resolving it.

**Comment by 2babooblabla** [comment] 2014-09-04 16:27
They are K2 Categorie links
do you want admin access?

**Comment by betweenbrain** [comment] 2014-09-04 16:44
Unfortunately, I need to run out for a family emergency and won't be able to check any time soon. If you can provide more details on how to reproduce the issue, for example with a clean install of Joomla and K2, that would be most helpful.

**Comment by 2babooblabla** [comment] 2014-09-04 16:57
Up until 116 menu items all is ok... 117 goes blanks..
independently of which items are published it seems.
Can't set up fresh install.. or at least would rather not take the time now if possible differently.
Let me know,
thanks!!!

**Comment by 2babooblabla** [comment] 2014-09-04 17:04
PS : goes blank only if menu-wrench is published
throwing the error at the top of this thread

**Comment by 2babooblabla** [comment] 2014-09-05 11:55
Hello again,

When you say you won't be able to work on it any time soon... can you tell me more?
Site needs to go online very soon and before duplicating the module a 100 times for every destination I need to be sure it will work.

thanks!!!

**Comment by betweenbrain** [comment] 2014-09-05 18:17
At this point, I can't reproduce the issue and the information you've given me doesn't lead me to any conclusion. The best I can do is guess what the problem may be. I've created a test site with over 117 menu items, some of which are K2 Category type, and no errors.

Based on the error, you should be able to pinpoint the exact menu item causing the issue and provide me with detailed information so that I can reproduce and address it.

**Comment by 2babooblabla** [comment] 2014-09-05 18:23
It does not seem to menu item related.
I can change the ones I unpublish and the ones I publish.
The problem remains the same when I reach 117.

I tryiing to dubbug more. I'll tell you if I find more.

I really hope we find a solution

thanks!

**Comment by 2babooblabla** [comment] 2014-09-05 18:26
ps : in my case they are all K2 links. I have no normal joomla links

**Comment by 2babooblabla** [comment] 2014-09-05 18:28
changing template or unpublishing other modules does not help

**Comment by betweenbrain** [comment] 2014-09-05 18:31
Are they all K2 Category menu types? What sort of configuration do they have?

**Comment by 2babooblabla** [comment] 2014-09-05 18:34
I have category and elements
All category links link to one single category.
What other settings do you want to know.
I can give you site access if you want

**Comment by 2babooblabla** [comment] 2014-09-05 18:39
just in case.. some items have images assigned to the link others dont

**Comment by betweenbrain** [comment] 2014-09-05 18:45
I can't reproduce with over 117 K2 Category menu items. I guess providing me access is the next option.

**Comment by 2babooblabla** [comment] 2014-09-05 18:48
ok sent by email.
I have unpiblished 1 more item again so site is functionnal

**Comment by 2babooblabla** [comment] 2014-09-06 08:38
the item limitition seems to be only in a specific menu.
I have another menu I use on the home page.. and if I unpublish items there it has no effect.

**Comment by 2babooblabla** [comment] 2014-09-06 09:13
Just to let you know. I think I found an alternative solution using main menu and having different menus with aliases to solve my problem. So I avoid using your module.
I haven't tested everything but should be ok.
Thank you very much for youre time.
I will get back in case my idea does not work.

**Closed as completed** 2014-09-06 18:27 UTC
